services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
      - './vhost.d:/etc/nginx/vhost.d:ro'
version: '2'
networks:
  default:
    external:
      name: services
